# Generated by Django 4.2.30 on 2026-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transacao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
