# Generated by Django 4.2.30 on 2026-05-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transacao_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustivel', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('rendimento_exato', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='fator_co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='km_estimado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RegistroEmissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_percorrida', models.FloatField()),
                ('co2_emitido_kg', models.FloatField()),
                ('usou_fallback', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.veiculo')),
            ],
        ),
    ]
