# Generated by Django 4.2.30 on 2026-05-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_veiculo_transacao_fator_co2_transacao_km_estimado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroemissao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('HATCH', 'Hatch Compacto (Leve)'), ('SEDAN', 'Sedan / SUV (Médio)'), ('UTILITARIO', 'Picape / Utilitário (Pesado)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('ETANOL', 'Etanol')], max_length=50),
        ),
    ]
