# Generated by Django 4.2.30 on 2026-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transacao_usuario_veiculo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
