# Generated by Django 4.2.30 on 2026-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_veiculo_ano_veiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('HATCH', 'Hatch Compacto (Leve)'), ('SEDAN', 'Sedan / SUV (Médio)'), ('UTILITARIO', 'Picape / Utilitário (Pesado)')], max_length=50, null=True),
        ),
    ]
