# Generated by Django 4.2.30 on 2026-06-04 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_veiculo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSustentabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='target', max_length=50)),
                ('objetivo_kg', models.FloatField(help_text='Quantos kg de CO2 economizar para bater a meta')),
            ],
        ),
        migrations.CreateModel(
            name='MetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso_kg', models.FloatField(default=0.0)),
                ('concluida', models.BooleanField(default=False)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metasustentabilidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
