# Generated by Django 4.2.30 on 2026-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('FATURADA', 'Faturada'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=10),
        ),
    ]
